### PR TITLE
feat: add nexus logo

### PR DESCRIPTION
**Pull request by gevuong**

### CODE REVIEW

**Review by a-wong-8 — APPROVED** [review]
@gevuong disregard the approval. the logos runs into each other

**Comment by a-wong-8** [comment]
and logos are too close together 

Screenshot 2024-10-10 at 12 37 56 PM
Screenshot 2024-10-10 at 12 37 32 PM

**Comment by gevuong** [comment]
This PR isn't the cause of those issues. That issue has likely been ongoing as the logos that were first added to the page overlap, and the styling for the container wrapping the logos remain unchanged for the past 18 months.

If you think it needs to be addressed, we can talk more about why, and if it makes sense, do so in a separate PR. But I don't think it's worth the time and effort to address the issue as the current focus is moving to 6.0.

**Comment by a-wong-8** [comment]
ok that makes sense

**Pull request merged**
